version: '3.7'

services:
  nginx:
    image: jobverplanke/nginx:1.19-alpine
    container_name: nginx
    environment:
      APP_DOMAIN: goals.test
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html:cached
    networks:
      - goals

  php:
    image: jobverplanke/php:7.4-fpm
    container_name: php
    environment:
      PHP_IDE_CONFIG: 'serverName=Docker' # Auto accept connections of IDE
    volumes:
      - ./:/var/www/html:cached
    networks:
      - goals

  mysql:
    image: library/mysql:8.0
    container_name: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-name-resolve
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      TZ: Europe/Amsterdam
    ports:
      - 3307:3306
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    networks:
      - goals

  redis:
    image: library/redis:6.0-alpine
    container_name: redis
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    ports:
      - 6379:6379
    volumes:
      - ./.docker/redis/data:/data
    networks:
      - goals

  mail:
    image: mailhog/mailhog:v1.0.1
    container_name: mail
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /var/log/fakesmtp
    volumes:
      - ./.docker/mail/data:/maildir
      - ./.docker/mail/logs:/var/log/fakesmtp
    networks:
      - goals

  whoami:
    image: traefik/whoami
    container_name: whoami
    networks:
      - goals

networks:
  goals:
    driver: bridge
