<?php

declare(strict_types=1);

namespace Domain\Objective\Http\Resources\Objective;

use Illuminate\Http\Resources\Json\ResourceCollection;

class ObjectiveResourceCollection extends ResourceCollection
{
    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}
